# Generated by Django 4.2.11 on 2025-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_tag_alter_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='is_nagative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questions.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_nagative',
            field=models.BooleanField(default=False),
        ),
    ]
