# Generated by Django 4.2.11 on 2025-11-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_answerlike_is_nagative_question_answers_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': 'Лайк ответа', 'verbose_name_plural': 'Лайки ответов'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': 'Лайк вопроса', 'verbose_name_plural': 'Лайки вопросов'},
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='question',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='is_nagative',
            new_name='is_negative',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='is_nagative',
            new_name='is_negative',
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('answer', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('question', 'author')},
        ),
    ]
