# Generated by Django 4.2.11 on 2025-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_answerlike_options_alter_questionlike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
    ]
